/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f4xx.h"
#include <string.h>
#include <stdio.h>
#include <math.h>

/* ── Defines ───────────────────────── */
#define WINDOW_SIZE    100
#define TH_SPATTER     2.1943f
#define TH_BURN_RMS    2.1607f
#define TH_INSTABILITY 0.2410f
#define TH_POROSITY    0.8000f
#define VREF           3.3f
#define ADC_MAX        4095.0f

/* ── Globals ───────────────────────── */
float    window[WINDOW_SIZE];
uint32_t win_idx = 0;
char     tx_buf[64];

/* ── UART2 Init ────────────────────── */
void UART2_Init(void) {
    /* Clock enable */
    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    /* PA2=TX, PA3=RX → AF7 */
    GPIOA->MODER  &= ~(0xF << 4);
    GPIOA->MODER  |=  (0xA << 4);
    GPIOA->AFR[0] |=  (7 << 8) | (7 << 12);

    /* 115200 baud @ 16MHz HSI */
    USART2->BRR = 0x008B;
    USART2->CR1 = USART_CR1_TE | USART_CR1_UE;
}

/* ── ADC1 Init (PA0) ───────────────── */
void ADC1_Init(void) {
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    /* PA0 = analog */
    GPIOA->MODER |= (3 << 0);

    ADC1->CR2  = ADC_CR2_ADON;
    ADC1->SQR3 = 0;  /* Channel 0 */
}

/* ── GPIO Init (PA5 = LED) ─────────── */
void GPIO_LED_Init(void) {
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    GPIOA->MODER &= ~(3 << 10);
    GPIOA->MODER |=  (1 << 10);
}

/* ── UART Send String ──────────────── */
void UART2_SendString(char *str) {
    while (*str) {
        while (!(USART2->SR & USART_SR_TXE));
        USART2->DR = *str++;
    }
}

/* ── ADC Read ──────────────────────── */
uint16_t ADC_Read(void) {
    ADC1->CR2 |= ADC_CR2_SWSTART;
    while (!(ADC1->SR & ADC_SR_EOC));
    return (uint16_t)ADC1->DR;
}

/* ── Simple Delay ──────────────────── */
void delay_ms(uint32_t ms) {
    for (uint32_t i = 0; i < ms * 1600; i++)
        __NOP();
}

/* ── Math helpers ──────────────────── */
float compute_rms(float *buf, uint32_t len) {
    float sum = 0;
    for (uint32_t i = 0; i < len; i++)
        sum += buf[i] * buf[i];
    return sqrtf(sum / len);
}

float compute_std(float *buf, uint32_t len) {
    float mean = 0, var = 0;
    for (uint32_t i = 0; i < len; i++)
        mean += buf[i];
    mean /= len;
    for (uint32_t i = 0; i < len; i++)
        var += (buf[i]-mean)*(buf[i]-mean);
    return sqrtf(var / len);
}

float find_min(float *buf, uint32_t len) {
    float m = buf[0];
    for (uint32_t i = 1; i < len; i++)
        if (buf[i] < m) m = buf[i];
    return m;
}

float find_max(float *buf, uint32_t len) {
    float m = buf[0];
    for (uint32_t i = 1; i < len; i++)
        if (buf[i] > m) m = buf[i];
    return m;
}

/* ── Main ──────────────────────────── */
int main(void) {
    UART2_Init();
    ADC1_Init();
    GPIO_LED_Init();

    UART2_SendString("Weld Monitor Started\r\n");

    while (1) {
        /* Read ADC → voltage */
        uint16_t raw = ADC_Read();
        float voltage = (raw / ADC_MAX) * VREF;

        /* Fill window */
        window[win_idx % WINDOW_SIZE] = voltage;
        win_idx++;

        if (win_idx >= WINDOW_SIZE) {
            float rms  = compute_rms(window, WINDOW_SIZE);
            float std  = compute_std(window, WINDOW_SIZE);
            float minV = find_min(window, WINDOW_SIZE);
            float maxV = find_max(window, WINDOW_SIZE);

            uint8_t sp = (maxV > TH_SPATTER)     ? 1:0;
            uint8_t bn = (rms  > TH_BURN_RMS)    ? 1:0;
            uint8_t in = (std  > TH_INSTABILITY) ? 1:0;
            uint8_t po = (minV < TH_POROSITY)     ? 1:0;

            /* LED toggle on defect */
            if (sp||bn||in||po)
                GPIOA->ODR ^= (1<<5);
            else
                GPIOA->ODR |= (1<<5);

            /* Send UART */
            snprintf(tx_buf, sizeof(tx_buf),
                "V:%.2f,R:%.2f,SP:%d,BN:%d,IN:%d,PO:%d\r\n",
                voltage, rms, sp, bn, in, po);
            UART2_SendString(tx_buf);
        }
        delay_ms(1);
    }
}
```

**STEP 3 — math library link karo:**
```
→ Project → Properties
→ C/C++ Build → Settings
→ Tool Settings → MCU GCC Linker → Libraries
→ Libraries (-l) → Add → m
→ Apply and Close
```

**STEP 4 — Build karo:**
```
→ Project → Build All (Ctrl+B)
→ 0 errors hone chahiye
